# Generated by Django 5.2.4 on 2025-09-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('windows', '0007_remove_windowconfiguration_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows.customerenquiry')),
            ],
            options={
                'unique_together': {('customer_enquiry',)},
            },
        ),
    ]
