# Generated by Django 5.2.4 on 2025-07-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0003_alter_fittingpriceoption_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='has_mosquito_net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windows.windowwidth'),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='mosquito_net_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MosquitoNetOption',
        ),
    ]
