# Generated by Django 5.2.4 on 2025-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0004_alter_customerenquiry_has_mosquito_net_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerenquiry',
            name='approximate_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
