# Generated by Django 5.2.4 on 2025-08-19 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0006_finish_hardware_infill_lock_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowconfiguration',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='windowconfiguration',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='windowconfiguration',
            name='infill',
        ),
        migrations.RemoveField(
            model_name='windowconfiguration',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='windowconfiguration',
            name='other',
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windows.finish'),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windows.hardware'),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='infill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windows.infill'),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windows.lock'),
        ),
        migrations.AddField(
            model_name='customerenquiry',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windows.other'),
        ),
    ]
