# Generated by Django 5.2.4 on 2025-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0007_remove_windowconfiguration_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerenquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved for Production'), ('in_production', 'In Production'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
